TwitchOverlays/Models/ErrorViewModel.cs
using System;

namespace TwitchOverlays.Models
{
	public class ErrorViewModel
	{
		public string RequestId { get; set; }

		public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
	}
}

TwitchOverlays/Controllers/AccountController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace TwitchOverlays.Controllers
{
	public class AccountController : Controller
	{

		[HttpGet]
		public IActionResult Login(string returnUrl = null)
		{
			ViewData["ReturnUrl"] = returnUrl;
			return View();
		}

		private bool ValidateLogin(string userName, string password)
		{
			return userName == "Kain_Stropov" && password == "MyLittleTwitch";
		}

		[HttpPost]
		public async Task<IActionResult> Login(string userName, string password, string returnUrl = null)
		{
			ViewData["ReturnUrl"] = returnUrl;

			// Normally Identity handles sign in, but you can do it directly
			if (ValidateLogin(userName, password))
			{
				var claims = new List<Claim>
				{
					new Claim(ClaimTypes.NameIdentifier, userName)
				};

				await HttpContext.SignInAsync(new ClaimsPrincipal(new ClaimsIdentity(claims, "Cookies")));

				if (Url.IsLocalUrl(returnUrl))
				{
					return Redirect(returnUrl);
				}
				else
				{
					return Redirect("/");
				}
			}

			return View();
		}

		public IActionResult AccessDenied(string returnUrl = null)
		{
			return View();
		}

		public async Task<IActionResult> Logout()
		{
			await HttpContext.SignOutAsync();
			return Redirect("/");
		}
	}
}

TwitchOverlays/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using TwitchOverlays.Models;

namespace TwitchOverlays.Controllers
{
	public class HomeController : Controller
	{
		private readonly ILogger<HomeController> _logger;

		public HomeController(ILogger<HomeController> logger)
		{
			_logger = logger;
		}

		public IActionResult Index()
		{
			return View();
		}

		public IActionResult Privacy()
		{
			return View();
		}

		[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
		public IActionResult Error()
		{
			return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
		}
	}
}

TwitchOverlays/Controllers/OverlayController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using TwitchOverlays.Filters;

namespace TwitchOverlays.Controllers
{
	[KeyFilter]
	public class OverlayController : Controller
	{
		public IActionResult Follower()
		{
			return View();
		}
	}
}

TwitchOverlays/Controllers/WebhooksController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.SignalR;
using Twitch.Utils.Twitch.Models;
using TwitchLib.Webhook;
using TwitchOverlays.Hubs;

namespace TwitchOverlays.Controllers
{
	public class WebhooksController : Controller
	{
		[TwitchWebHook(Id = "followers")]
		public async Task<IActionResult> Followers([FromServices] IHubContext<OverlayHub> hubContext, [FromBody] UserFollowsModel data)
		{
			await hubContext.Clients.All.SendAsync("newFollower", data.Followers.First().FromUser);
			return Ok();
		}
	}
}

TwitchOverlays/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

TwitchOverlays/Views/Overlay/Follower.cshtml
@{
	Layout = null;
}

<!DOCTYPE html>

<html>
<head>
	<meta name="viewport" content="width=device-width" />
	<title>Follower</title>
	<style>
		body {
			background-color: black;
		}

		.base {
			opacity: 0;
			transition: opacity 1s;
		}

		.shown {
			opacity: 1 !important;
		}

		.border {
			border: solid black 1px;
		}

		.cont {
			display: flex;
			align-content: center;
			background-color: white;
			border-radius: 20px;
			width: 520px;
		}

		.message {
			margin-top: auto;
			margin-bottom: auto;
			font-size: 50px;
		}

		.img-cont {
			height: 200px;
			width: 200px;
		}

		img {
			height: 100%;
			width: 100%;
		}
	</style>
</head>
<body>
	<div class="cont border base">
		<div class="img-cont">
			<img src="~/img/doomer_walk.gif" />
		</div>
		<div id="message" class="message" style="">
			New follower:
			<div id="follower"></div>
		</div>
	</div>


	<script src="~/lib/jquery/jquery.js"></script>
	<script src="~/lib/signalr/dist/browser/signalr.js"></script>
	<script>
		"use strict";

		const connection = new signalR.HubConnectionBuilder().withUrl("/overlay").build();
		const cont = $(".base");
		const followersQueue = [];
		let displayIsBusy = false;
		connection.on("newFollower", function (name) {
			followersQueue.push(name);
		});

		setInterval(() => {
			if (displayIsBusy) return;
			const follower = followersQueue.shift();
			if (!follower) return;
			displayIsBusy = true;
			$("#follower").text(follower);
			cont.addClass("shown")
			setTimeout(() => {
				cont.removeClass("shown");
				displayIsBusy = false;
			}, 3000)
		}, 1000);

		connection.start().then(function () {
		}).catch(function (err) {
			return console.error(err.toString());
		});
	</script>
</body>
</html>

TwitchOverlays/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<title>@ViewData["Title"] - TwitchOverlays</title>
	<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
	<link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
	<header>
		<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
			<div class="container">
				<a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">TwitchOverlays</a>
				<button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
						aria-expanded="false" aria-label="Toggle navigation">
					<span class="navbar-toggler-icon"></span>
				</button>
				<div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
					<ul class="navbar-nav flex-grow-1">
						<li class="nav-item">
							<a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
						</li>
						@if (User.Identity.IsAuthenticated)
						{
							<li class="nav-item dropdown">
								<a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
								</a>
								<div class="dropdown-menu" aria-labelledby="navbarDropdown">
									<a class="dropdown-item" asp-action="Follower" asp-controller="Overlay"></a>
								</div>
							</li>
							<li class="nav-item"><a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Logout">Logout</a></li>
						}
						else
						{
							<li class="nav-item"><a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Login">Login</a></li>
						}
					</ul>
				</div>
			</div>
		</nav>
	</header>
	<div class="container">
		<main role="main" class="pb-3">
			@RenderBody()
		</main>
	</div>

	<footer class="border-top footer text-muted">
		<div class="container">
			&copy; 2019 - TwitchOverlays - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
		</div>
	</footer>
	<script src="~/lib/jquery/jquery.js"></script>
	<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
	<script src="~/js/site.js" asp-append-version="true"></script>
	@RenderSection("Scripts", required: false)
</body>
</html>