Twitch/Models/ErrorViewModel.cs
using System;

namespace Twitch.Models
{
	public class ErrorViewModel
	{
		public string RequestId { get; set; }

		public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
	}
}

Twitch/Controllers/AuthController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace Twitch.Controllers
{
    public class AuthController : Controller
    {
        public IActionResult Auth()
        {
            return View();
        }

		public IActionResult Callback()
		{
			return Ok();
		}
    }
}

Twitch/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Twitch.Models;

namespace Twitch.Controllers
{
	public class HomeController : Controller
	{
		private readonly ILogger<HomeController> _logger;

		public HomeController(ILogger<HomeController> logger)
		{
			_logger = logger;
		}

		public IActionResult Index()
		{
			return View();
		}

		public IActionResult Privacy()
		{
			return View();
		}

		[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
		public IActionResult Error()
		{
			return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
		}
	}
}

Twitch/Controllers/InfoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Twitch.Utils.Twitch;

namespace Twitch.Controllers
{
	public class InfoController : Controller
	{
		private readonly TwitchHelper _helper;

		public InfoController(TwitchHelper helper)
		{
			_helper = helper;
		}

		public async Task<IActionResult> Followers()
		{
			return View(await _helper.GetUserFollows("52963431"));
		}
	}
}

Twitch/Controllers/SubscribitionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Twitch.Utils.Twitch;

namespace Twitch.Controllers
{
	public class SubscribitionController : Controller
	{
		private readonly TwitchHelper _helper;

		public SubscribitionController(TwitchHelper helper)
		{
			_helper = helper;
		}

		public IActionResult Index()
		{
			return View();
		}

		public async Task<IActionResult> Followers()
		{
			ViewBag.WasException = false;
			try
			{
				await _helper.SubscribeToFollowers("52963431");
			}
			catch (Exception e)
			{
				ViewBag.WasException = true;
			}
			return View();
		}
	}
}

Twitch/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Twitch/Views/Info/Followers.cshtml
@model Twitch.Utils.Twitch.Models.UserFollowsModel
@{
	ViewData["Title"] = "Followers";
}

<h1>Followers</h1>

<ul>
	@foreach (var follower in Model.Followers)
	{
	<li>@follower.FromUser (@follower.FollowerAt.ToShortDateString())</li>
	}
</ul>

Twitch/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<title>@ViewData["Title"] - Twitch</title>
	<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
	<link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
	<header>
		<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
			<div class="container">
				<a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Twitch</a>
				<button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
						aria-expanded="false" aria-label="Toggle navigation">
					<span class="navbar-toggler-icon"></span>
				</button>
				<div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
					<ul class="navbar-nav flex-grow-1">
						<li class="nav-item">
							<a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
						</li>
						<li class="nav-item">
							<a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
						</li>
						<li class="nav-item dropdown">
							<a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
								Info
							</a>
							<div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
								<a class="dropdown-item" asp-controller="Info" asp-action="Followers">Followers</a>
							</div>
						<li class="nav-item dropdown">
							<a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
								Subscriptions
							</a>
							<div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
								<a class="dropdown-item" asp-controller="Subscribition" asp-action="Followers">Followers</a>
							</div>
						</li>
						</li>
					</ul>
				</div>
			</div>
		</nav>
	</header>
	<div class="container">
		<main role="main" class="pb-3">
			@RenderBody()
		</main>
	</div>

	<footer class="border-top footer text-muted">
		<div class="container">
			&copy; 2019 - Twitch - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
		</div>
	</footer>
	<script src="~/lib/jquery/dist/jquery.min.js"></script>
	<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
	<script src="~/js/site.js" asp-append-version="true"></script>
	@RenderSection("Scripts", required: false)
</body>
</html>

Twitch/Views/Subscribition/Followers.cshtml
@{
	ViewData["Title"] = "Followers";
}

<h1>Followers</h1>

<p>
	@if (ViewBag.WasException)
	{
		<text>Was exception</text>
	}
	else
	{
		<text>Ok</text>
	}
</p>